/**
 * Sync app version from ./VERSION into package.json / package-lock (root only),
 * Cargo.toml, tauri.conf.json, app/src/version.ts
 *
 * Usage: node sync_version.js [x.y.z]
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;
const versionFile = path.join(root, "VERSION");
let version = (process.argv[2] || "").trim();

if (version) {
  fs.writeFileSync(versionFile, version + "\n", "utf8");
} else {
  version = fs.readFileSync(versionFile, "utf8").trim();
}

if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`invalid version: ${version}`);
  process.exit(1);
}

// package.json — app version only
const pkgPath = path.join(root, "app", "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
pkg.version = version;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");

// package-lock.json — root package version only (never touch deps)
const lockPath = path.join(root, "app", "package-lock.json");
if (fs.existsSync(lockPath)) {
  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  lock.version = version;
  if (lock.packages && lock.packages[""]) {
    lock.packages[""].version = version;
  }
  fs.writeFileSync(lockPath, JSON.stringify(lock, null, 2) + "\n", "utf8");
}

// Cargo.toml
const cargoPath = path.join(root, "app", "src-tauri", "Cargo.toml");
let cargo = fs.readFileSync(cargoPath, "utf8");
cargo = cargo.replace(/^version\s*=\s*"[^"]+"/m, `version = "${version}"`);
fs.writeFileSync(cargoPath, cargo, "utf8");

// tauri.conf.json
const tauriPath = path.join(root, "app", "src-tauri", "tauri.conf.json");
let tauri = fs.readFileSync(tauriPath, "utf8");
tauri = tauri.replace(/^(\s*"version"\s*:\s*")[^"]+(")/m, `$1${version}$2`);
fs.writeFileSync(tauriPath, tauri, "utf8");

// frontend
const verTs = path.join(root, "app", "src", "version.ts");
fs.writeFileSync(
  verTs,
  `/** Auto-generated by sync_version.js from /VERSION - do not edit. */\nexport const APP_VERSION = "${version}";\n`,
  "utf8"
);

console.log(`Synced version -> ${version}`);
console.log("  VERSION, package.json, package-lock (root), Cargo.toml, tauri.conf.json, version.ts");
